#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="RegistroCivil")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertAudio(Audio instance);
  partial void UpdateAudio(Audio instance);
  partial void DeleteAudio(Audio instance);
  partial void InsertImagene(Imagene instance);
  partial void UpdateImagene(Imagene instance);
  partial void DeleteImagene(Imagene instance);
  partial void InsertVideo(Video instance);
  partial void UpdateVideo(Video instance);
  partial void DeleteVideo(Video instance);
  partial void InsertPersona(Persona instance);
  partial void UpdatePersona(Persona instance);
  partial void DeletePersona(Persona instance);
  partial void InsertPai(Pai instance);
  partial void UpdatePai(Pai instance);
  partial void DeletePai(Pai instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["RegistroCivilConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Audio> Audios
	{
		get
		{
			return this.GetTable<Audio>();
		}
	}
	
	public System.Data.Linq.Table<Imagene> Imagenes
	{
		get
		{
			return this.GetTable<Imagene>();
		}
	}
	
	public System.Data.Linq.Table<Video> Videos
	{
		get
		{
			return this.GetTable<Video>();
		}
	}
	
	public System.Data.Linq.Table<Persona> Personas
	{
		get
		{
			return this.GetTable<Persona>();
		}
	}
	
	public System.Data.Linq.Table<Pai> Pais
	{
		get
		{
			return this.GetTable<Pai>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Audios")]
public partial class Audio : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _descripcion;
	
	private System.Data.Linq.Binary _info_bytes;
	
	private EntitySet<Pai> _Pais;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void Oninfo_bytesChanging(System.Data.Linq.Binary value);
    partial void Oninfo_bytesChanged();
    #endregion
	
	public Audio()
	{
		this._Pais = new EntitySet<Pai>(new Action<Pai>(this.attach_Pais), new Action<Pai>(this.detach_Pais));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(50)")]
	public string descripcion
	{
		get
		{
			return this._descripcion;
		}
		set
		{
			if ((this._descripcion != value))
			{
				this.OndescripcionChanging(value);
				this.SendPropertyChanging();
				this._descripcion = value;
				this.SendPropertyChanged("descripcion");
				this.OndescripcionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_info_bytes", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public System.Data.Linq.Binary info_bytes
	{
		get
		{
			return this._info_bytes;
		}
		set
		{
			if ((this._info_bytes != value))
			{
				this.Oninfo_bytesChanging(value);
				this.SendPropertyChanging();
				this._info_bytes = value;
				this.SendPropertyChanged("info_bytes");
				this.Oninfo_bytesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Audio_Pai", Storage="_Pais", ThisKey="id", OtherKey="himnoNacional")]
	public EntitySet<Pai> Pais
	{
		get
		{
			return this._Pais;
		}
		set
		{
			this._Pais.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Pais(Pai entity)
	{
		this.SendPropertyChanging();
		entity.Audio = this;
	}
	
	private void detach_Pais(Pai entity)
	{
		this.SendPropertyChanging();
		entity.Audio = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Imagenes")]
public partial class Imagene : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _descripcion;
	
	private System.Data.Linq.Binary _info_bytes;
	
	private EntitySet<Persona> _Personas;
	
	private EntitySet<Pai> _Pais;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void Oninfo_bytesChanging(System.Data.Linq.Binary value);
    partial void Oninfo_bytesChanged();
    #endregion
	
	public Imagene()
	{
		this._Personas = new EntitySet<Persona>(new Action<Persona>(this.attach_Personas), new Action<Persona>(this.detach_Personas));
		this._Pais = new EntitySet<Pai>(new Action<Pai>(this.attach_Pais), new Action<Pai>(this.detach_Pais));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(50)")]
	public string descripcion
	{
		get
		{
			return this._descripcion;
		}
		set
		{
			if ((this._descripcion != value))
			{
				this.OndescripcionChanging(value);
				this.SendPropertyChanging();
				this._descripcion = value;
				this.SendPropertyChanged("descripcion");
				this.OndescripcionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_info_bytes", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public System.Data.Linq.Binary info_bytes
	{
		get
		{
			return this._info_bytes;
		}
		set
		{
			if ((this._info_bytes != value))
			{
				this.Oninfo_bytesChanging(value);
				this.SendPropertyChanging();
				this._info_bytes = value;
				this.SendPropertyChanged("info_bytes");
				this.Oninfo_bytesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Imagene_Persona", Storage="_Personas", ThisKey="id", OtherKey="foto")]
	public EntitySet<Persona> Personas
	{
		get
		{
			return this._Personas;
		}
		set
		{
			this._Personas.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Imagene_Pai", Storage="_Pais", ThisKey="id", OtherKey="fotoBandera")]
	public EntitySet<Pai> Pais
	{
		get
		{
			return this._Pais;
		}
		set
		{
			this._Pais.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Personas(Persona entity)
	{
		this.SendPropertyChanging();
		entity.Imagene = this;
	}
	
	private void detach_Personas(Persona entity)
	{
		this.SendPropertyChanging();
		entity.Imagene = null;
	}
	
	private void attach_Pais(Pai entity)
	{
		this.SendPropertyChanging();
		entity.Imagene = this;
	}
	
	private void detach_Pais(Pai entity)
	{
		this.SendPropertyChanging();
		entity.Imagene = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Videos")]
public partial class Video : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _descripcion;
	
	private System.Data.Linq.Binary _info_bytes;
	
	private EntitySet<Persona> _Personas;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void Oninfo_bytesChanging(System.Data.Linq.Binary value);
    partial void Oninfo_bytesChanged();
    #endregion
	
	public Video()
	{
		this._Personas = new EntitySet<Persona>(new Action<Persona>(this.attach_Personas), new Action<Persona>(this.detach_Personas));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(50)")]
	public string descripcion
	{
		get
		{
			return this._descripcion;
		}
		set
		{
			if ((this._descripcion != value))
			{
				this.OndescripcionChanging(value);
				this.SendPropertyChanging();
				this._descripcion = value;
				this.SendPropertyChanged("descripcion");
				this.OndescripcionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_info_bytes", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public System.Data.Linq.Binary info_bytes
	{
		get
		{
			return this._info_bytes;
		}
		set
		{
			if ((this._info_bytes != value))
			{
				this.Oninfo_bytesChanging(value);
				this.SendPropertyChanging();
				this._info_bytes = value;
				this.SendPropertyChanged("info_bytes");
				this.Oninfo_bytesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Video_Persona", Storage="_Personas", ThisKey="id", OtherKey="videoEntrevista")]
	public EntitySet<Persona> Personas
	{
		get
		{
			return this._Personas;
		}
		set
		{
			this._Personas.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Personas(Persona entity)
	{
		this.SendPropertyChanging();
		entity.Video = this;
	}
	
	private void detach_Personas(Persona entity)
	{
		this.SendPropertyChanging();
		entity.Video = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Persona")]
public partial class Persona : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private decimal _idPersona;
	
	private string _nbrPersona;
	
	private decimal _idPaisNacimiento;
	
	private decimal _idPaisResidencia;
	
	private System.DateTime _fchNacimiento;
	
	private string _correo;
	
	private int _foto;
	
	private System.Nullable<int> _videoEntrevista;
	
	private EntityRef<Video> _Video;
	
	private EntityRef<Imagene> _Imagene;
	
	private EntityRef<Pai> _Pai;
	
	private EntityRef<Pai> _Pai1;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPersonaChanging(decimal value);
    partial void OnidPersonaChanged();
    partial void OnnbrPersonaChanging(string value);
    partial void OnnbrPersonaChanged();
    partial void OnidPaisNacimientoChanging(decimal value);
    partial void OnidPaisNacimientoChanged();
    partial void OnidPaisResidenciaChanging(decimal value);
    partial void OnidPaisResidenciaChanged();
    partial void OnfchNacimientoChanging(System.DateTime value);
    partial void OnfchNacimientoChanged();
    partial void OncorreoChanging(string value);
    partial void OncorreoChanged();
    partial void OnfotoChanging(int value);
    partial void OnfotoChanged();
    partial void OnvideoEntrevistaChanging(System.Nullable<int> value);
    partial void OnvideoEntrevistaChanged();
    #endregion
	
	public Persona()
	{
		this._Video = default(EntityRef<Video>);
		this._Imagene = default(EntityRef<Imagene>);
		this._Pai = default(EntityRef<Pai>);
		this._Pai1 = default(EntityRef<Pai>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPersona", DbType="Decimal(10,0) NOT NULL", IsPrimaryKey=true)]
	public decimal idPersona
	{
		get
		{
			return this._idPersona;
		}
		set
		{
			if ((this._idPersona != value))
			{
				this.OnidPersonaChanging(value);
				this.SendPropertyChanging();
				this._idPersona = value;
				this.SendPropertyChanged("idPersona");
				this.OnidPersonaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nbrPersona", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string nbrPersona
	{
		get
		{
			return this._nbrPersona;
		}
		set
		{
			if ((this._nbrPersona != value))
			{
				this.OnnbrPersonaChanging(value);
				this.SendPropertyChanging();
				this._nbrPersona = value;
				this.SendPropertyChanged("nbrPersona");
				this.OnnbrPersonaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPaisNacimiento", DbType="Decimal(3,0) NOT NULL")]
	public decimal idPaisNacimiento
	{
		get
		{
			return this._idPaisNacimiento;
		}
		set
		{
			if ((this._idPaisNacimiento != value))
			{
				if (this._Pai.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnidPaisNacimientoChanging(value);
				this.SendPropertyChanging();
				this._idPaisNacimiento = value;
				this.SendPropertyChanged("idPaisNacimiento");
				this.OnidPaisNacimientoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPaisResidencia", DbType="Decimal(3,0) NOT NULL", IsPrimaryKey=true)]
	public decimal idPaisResidencia
	{
		get
		{
			return this._idPaisResidencia;
		}
		set
		{
			if ((this._idPaisResidencia != value))
			{
				if (this._Pai1.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnidPaisResidenciaChanging(value);
				this.SendPropertyChanging();
				this._idPaisResidencia = value;
				this.SendPropertyChanged("idPaisResidencia");
				this.OnidPaisResidenciaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fchNacimiento", DbType="Date NOT NULL")]
	public System.DateTime fchNacimiento
	{
		get
		{
			return this._fchNacimiento;
		}
		set
		{
			if ((this._fchNacimiento != value))
			{
				this.OnfchNacimientoChanging(value);
				this.SendPropertyChanging();
				this._fchNacimiento = value;
				this.SendPropertyChanged("fchNacimiento");
				this.OnfchNacimientoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(150)")]
	public string correo
	{
		get
		{
			return this._correo;
		}
		set
		{
			if ((this._correo != value))
			{
				this.OncorreoChanging(value);
				this.SendPropertyChanging();
				this._correo = value;
				this.SendPropertyChanged("correo");
				this.OncorreoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foto", DbType="Int NOT NULL")]
	public int foto
	{
		get
		{
			return this._foto;
		}
		set
		{
			if ((this._foto != value))
			{
				if (this._Imagene.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnfotoChanging(value);
				this.SendPropertyChanging();
				this._foto = value;
				this.SendPropertyChanged("foto");
				this.OnfotoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_videoEntrevista", DbType="Int")]
	public System.Nullable<int> videoEntrevista
	{
		get
		{
			return this._videoEntrevista;
		}
		set
		{
			if ((this._videoEntrevista != value))
			{
				if (this._Video.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnvideoEntrevistaChanging(value);
				this.SendPropertyChanging();
				this._videoEntrevista = value;
				this.SendPropertyChanged("videoEntrevista");
				this.OnvideoEntrevistaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Video_Persona", Storage="_Video", ThisKey="videoEntrevista", OtherKey="id", IsForeignKey=true)]
	public Video Video
	{
		get
		{
			return this._Video.Entity;
		}
		set
		{
			Video previousValue = this._Video.Entity;
			if (((previousValue != value) 
						|| (this._Video.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Video.Entity = null;
					previousValue.Personas.Remove(this);
				}
				this._Video.Entity = value;
				if ((value != null))
				{
					value.Personas.Add(this);
					this._videoEntrevista = value.id;
				}
				else
				{
					this._videoEntrevista = default(Nullable<int>);
				}
				this.SendPropertyChanged("Video");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Imagene_Persona", Storage="_Imagene", ThisKey="foto", OtherKey="id", IsForeignKey=true)]
	public Imagene Imagene
	{
		get
		{
			return this._Imagene.Entity;
		}
		set
		{
			Imagene previousValue = this._Imagene.Entity;
			if (((previousValue != value) 
						|| (this._Imagene.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Imagene.Entity = null;
					previousValue.Personas.Remove(this);
				}
				this._Imagene.Entity = value;
				if ((value != null))
				{
					value.Personas.Add(this);
					this._foto = value.id;
				}
				else
				{
					this._foto = default(int);
				}
				this.SendPropertyChanged("Imagene");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pai_Persona", Storage="_Pai", ThisKey="idPaisNacimiento", OtherKey="idPais", IsForeignKey=true)]
	public Pai Pai
	{
		get
		{
			return this._Pai.Entity;
		}
		set
		{
			Pai previousValue = this._Pai.Entity;
			if (((previousValue != value) 
						|| (this._Pai.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Pai.Entity = null;
					previousValue.Personas.Remove(this);
				}
				this._Pai.Entity = value;
				if ((value != null))
				{
					value.Personas.Add(this);
					this._idPaisNacimiento = value.idPais;
				}
				else
				{
					this._idPaisNacimiento = default(decimal);
				}
				this.SendPropertyChanged("Pai");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pai_Persona1", Storage="_Pai1", ThisKey="idPaisResidencia", OtherKey="idPais", IsForeignKey=true)]
	public Pai Pai1
	{
		get
		{
			return this._Pai1.Entity;
		}
		set
		{
			Pai previousValue = this._Pai1.Entity;
			if (((previousValue != value) 
						|| (this._Pai1.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Pai1.Entity = null;
					previousValue.Personas1.Remove(this);
				}
				this._Pai1.Entity = value;
				if ((value != null))
				{
					value.Personas1.Add(this);
					this._idPaisResidencia = value.idPais;
				}
				else
				{
					this._idPaisResidencia = default(decimal);
				}
				this.SendPropertyChanged("Pai1");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pais")]
public partial class Pai : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private decimal _idPais;
	
	private string _nbrPais;
	
	private decimal _area;
	
	private decimal _poblacionActual;
	
	private int _fotoBandera;
	
	private int _himnoNacional;
	
	private System.Nullable<decimal> _idPresidenteActual;
	
	private EntitySet<Persona> _Personas;
	
	private EntitySet<Persona> _Personas1;
	
	private EntityRef<Imagene> _Imagene;
	
	private EntityRef<Audio> _Audio;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPaisChanging(decimal value);
    partial void OnidPaisChanged();
    partial void OnnbrPaisChanging(string value);
    partial void OnnbrPaisChanged();
    partial void OnareaChanging(decimal value);
    partial void OnareaChanged();
    partial void OnpoblacionActualChanging(decimal value);
    partial void OnpoblacionActualChanged();
    partial void OnfotoBanderaChanging(int value);
    partial void OnfotoBanderaChanged();
    partial void OnhimnoNacionalChanging(int value);
    partial void OnhimnoNacionalChanged();
    partial void OnidPresidenteActualChanging(System.Nullable<decimal> value);
    partial void OnidPresidenteActualChanged();
    #endregion
	
	public Pai()
	{
		this._Personas = new EntitySet<Persona>(new Action<Persona>(this.attach_Personas), new Action<Persona>(this.detach_Personas));
		this._Personas1 = new EntitySet<Persona>(new Action<Persona>(this.attach_Personas1), new Action<Persona>(this.detach_Personas1));
		this._Imagene = default(EntityRef<Imagene>);
		this._Audio = default(EntityRef<Audio>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPais", DbType="Decimal(3,0) NOT NULL", IsPrimaryKey=true)]
	public decimal idPais
	{
		get
		{
			return this._idPais;
		}
		set
		{
			if ((this._idPais != value))
			{
				this.OnidPaisChanging(value);
				this.SendPropertyChanging();
				this._idPais = value;
				this.SendPropertyChanged("idPais");
				this.OnidPaisChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nbrPais", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string nbrPais
	{
		get
		{
			return this._nbrPais;
		}
		set
		{
			if ((this._nbrPais != value))
			{
				this.OnnbrPaisChanging(value);
				this.SendPropertyChanging();
				this._nbrPais = value;
				this.SendPropertyChanged("nbrPais");
				this.OnnbrPaisChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_area", DbType="Decimal(12,2) NOT NULL")]
	public decimal area
	{
		get
		{
			return this._area;
		}
		set
		{
			if ((this._area != value))
			{
				this.OnareaChanging(value);
				this.SendPropertyChanging();
				this._area = value;
				this.SendPropertyChanged("area");
				this.OnareaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_poblacionActual", DbType="Decimal(10,0) NOT NULL")]
	public decimal poblacionActual
	{
		get
		{
			return this._poblacionActual;
		}
		set
		{
			if ((this._poblacionActual != value))
			{
				this.OnpoblacionActualChanging(value);
				this.SendPropertyChanging();
				this._poblacionActual = value;
				this.SendPropertyChanged("poblacionActual");
				this.OnpoblacionActualChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fotoBandera", DbType="Int NOT NULL")]
	public int fotoBandera
	{
		get
		{
			return this._fotoBandera;
		}
		set
		{
			if ((this._fotoBandera != value))
			{
				if (this._Imagene.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnfotoBanderaChanging(value);
				this.SendPropertyChanging();
				this._fotoBandera = value;
				this.SendPropertyChanged("fotoBandera");
				this.OnfotoBanderaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_himnoNacional", DbType="Int NOT NULL")]
	public int himnoNacional
	{
		get
		{
			return this._himnoNacional;
		}
		set
		{
			if ((this._himnoNacional != value))
			{
				if (this._Audio.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnhimnoNacionalChanging(value);
				this.SendPropertyChanging();
				this._himnoNacional = value;
				this.SendPropertyChanged("himnoNacional");
				this.OnhimnoNacionalChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPresidenteActual", DbType="Decimal(10,0)")]
	public System.Nullable<decimal> idPresidenteActual
	{
		get
		{
			return this._idPresidenteActual;
		}
		set
		{
			if ((this._idPresidenteActual != value))
			{
				this.OnidPresidenteActualChanging(value);
				this.SendPropertyChanging();
				this._idPresidenteActual = value;
				this.SendPropertyChanged("idPresidenteActual");
				this.OnidPresidenteActualChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pai_Persona", Storage="_Personas", ThisKey="idPais", OtherKey="idPaisNacimiento")]
	public EntitySet<Persona> Personas
	{
		get
		{
			return this._Personas;
		}
		set
		{
			this._Personas.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pai_Persona1", Storage="_Personas1", ThisKey="idPais", OtherKey="idPaisResidencia")]
	public EntitySet<Persona> Personas1
	{
		get
		{
			return this._Personas1;
		}
		set
		{
			this._Personas1.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Imagene_Pai", Storage="_Imagene", ThisKey="fotoBandera", OtherKey="id", IsForeignKey=true)]
	public Imagene Imagene
	{
		get
		{
			return this._Imagene.Entity;
		}
		set
		{
			Imagene previousValue = this._Imagene.Entity;
			if (((previousValue != value) 
						|| (this._Imagene.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Imagene.Entity = null;
					previousValue.Pais.Remove(this);
				}
				this._Imagene.Entity = value;
				if ((value != null))
				{
					value.Pais.Add(this);
					this._fotoBandera = value.id;
				}
				else
				{
					this._fotoBandera = default(int);
				}
				this.SendPropertyChanged("Imagene");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Audio_Pai", Storage="_Audio", ThisKey="himnoNacional", OtherKey="id", IsForeignKey=true)]
	public Audio Audio
	{
		get
		{
			return this._Audio.Entity;
		}
		set
		{
			Audio previousValue = this._Audio.Entity;
			if (((previousValue != value) 
						|| (this._Audio.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Audio.Entity = null;
					previousValue.Pais.Remove(this);
				}
				this._Audio.Entity = value;
				if ((value != null))
				{
					value.Pais.Add(this);
					this._himnoNacional = value.id;
				}
				else
				{
					this._himnoNacional = default(int);
				}
				this.SendPropertyChanged("Audio");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Personas(Persona entity)
	{
		this.SendPropertyChanging();
		entity.Pai = this;
	}
	
	private void detach_Personas(Persona entity)
	{
		this.SendPropertyChanging();
		entity.Pai = null;
	}
	
	private void attach_Personas1(Persona entity)
	{
		this.SendPropertyChanging();
		entity.Pai1 = this;
	}
	
	private void detach_Personas1(Persona entity)
	{
		this.SendPropertyChanging();
		entity.Pai1 = null;
	}
}
#pragma warning restore 1591
