//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appRegistroCivil.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RegistroCivilEntities : DbContext
    {
        public RegistroCivilEntities()
            : base("name=RegistroCivilEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<apellidos> apellidos { get; set; }
        public virtual DbSet<Audios> Audios { get; set; }
        public virtual DbSet<Imagenes> Imagenes { get; set; }
        public virtual DbSet<nombres> nombres { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<Videos> Videos { get; set; }
    
        public virtual ObjectResult<SP_EdadPromedio1_Result> SP_EdadPromedio()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_EdadPromedio1_Result>("SP_EdadPromedio");
        }
    
        public virtual int SP_GenerarPersonas(Nullable<int> cantidadPaises, Nullable<int> personasxPais)
        {
            var cantidadPaisesParameter = cantidadPaises.HasValue ?
                new ObjectParameter("cantidadPaises", cantidadPaises) :
                new ObjectParameter("cantidadPaises", typeof(int));
    
            var personasxPaisParameter = personasxPais.HasValue ?
                new ObjectParameter("personasxPais", personasxPais) :
                new ObjectParameter("personasxPais", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GenerarPersonas", cantidadPaisesParameter, personasxPaisParameter);
        }
    
        public virtual ObjectResult<SP_Nacimientos_Result> SP_Nacimientos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Nacimientos_Result>("SP_Nacimientos");
        }
    
        public virtual ObjectResult<SP_EdadPromedio1_Result> SP_EdadPromedio1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_EdadPromedio1_Result>("SP_EdadPromedio1");
        }
    }
}
