//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appRegistroCivil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pais
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pais()
        {
            this.Persona = new HashSet<Persona>();
            this.Persona1 = new HashSet<Persona>();
        }
    
        public decimal idPais { get; set; }
        public string nbrPais { get; set; }
        public decimal area { get; set; }
        public decimal poblacionActual { get; set; }
        public int fotoBandera { get; set; }
        public int himnoNacional { get; set; }
        public Nullable<decimal> idPresidenteActual { get; set; }
    
        public virtual Audios Audios { get; set; }
        public virtual Imagenes Imagenes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Persona> Persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Persona> Persona1 { get; set; }
    }
}
