//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appRegistroCivil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public decimal idPersona { get; set; }
        public string nbrPersona { get; set; }
        public decimal idPaisNacimiento { get; set; }
        public decimal idPaisResidencia { get; set; }
        public System.DateTime fchNacimiento { get; set; }
        public string correo { get; set; }
        public int foto { get; set; }
        public Nullable<int> videoEntrevista { get; set; }
    
        public virtual Imagenes Imagenes { get; set; }
        public virtual Pais Pais { get; set; }
        public virtual Pais Pais1 { get; set; }
        public virtual Videos Videos { get; set; }
    }
}
